#ifndef RDBS_PARAMS_H
#define RDBS_PARAMS_H

// Auto-generated by MATLAB fixed-point model
// Scan cone: +/- 45 degrees

#define M_ELEMENTS   64    // total antenna elements
#define B_BEAMS      21    // kept beams after RDBS
#define K_SNAPSHOTS  1000    // time snapshots
#define BW_DATA      16    // input bit width
#define BW_OUT       16    // output bit width
#define BW_COEFF     16    // coefficient bit width
#define BW_ACCUM     32    // accumulator bit width
#define INT_IN       1    // input integer bits (ap_fixed<16,1>)
#define INT_OUT      4    // output integer bits (ap_fixed<16,4>)
#define FRAC_DATA    15    // fractional bits for input
#define FRAC_OUT     12    // fractional bits for output
#define FRAC_COEFF   15    // fractional bits for coeffs
#define X_SCALE      45.0958793716 // multiply HLS output by this to get volts

#endif